site_name: Pocket

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro

nav:
  - Contextualização: index.md
  - Temas IHC:
      - UX/UI Design: TemasIHC/UX & UI Design.md
      - Personas: TemasIHC/Personas.md
      - User Journey X User Flows: TemasIHC/User Journey X User Flows.md
      - BluePrint: TemasIHC/BluePrint.md
      - Design Empático: TemasIHC/Design Empatico.md
  - CheckList:
      - Desenvolvimento Web: CheckList/Desenvolvimento Web.md
      - Design e Conteúdo: CheckList/Design.md
      - Ferramentas de Acessibilidade: CheckList/Ferramentas de Acessibilidade.md
      - Geração de Conteúdo: CheckList/Geração de Conteudo.md
      - Gestão de Projetos: CheckList/Gestao de Projetos.md
      - Heurística de Nielsen: CheckList/Heuristica de Nielsen.md
      - Resultado da Acessibilidade: CheckList/Resultado da Acessibilidade.md
  - Entrevista:
      - Think Aloud: Entrevista/Think Aloud.md
      - Roteiro: Entrevista/Roteiro.md
      - Referencias: Entrevista/Referencias.md

extra_css:
  - assets/css/checklist.css
  - assets/css/contribuidores.css

extra_javascript:
  - assets/js/checklist-database.js
  - assets/js/checklist-manager.js

hooks:
  - auto_database.py